# Generated by Django 5.1.3 on 2024-11-13 08:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название областей')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание гайда')),
                ('image', models.CharField(max_length=500, verbose_name='URL-фото')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Гайд',
                'verbose_name_plural': 'Гайды',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('tsar', models.CharField(max_length=100, verbose_name='Цель')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('task', models.CharField(max_length=255, verbose_name='задание')),
                ('answer', models.CharField(max_length=255, verbose_name='ответ')),
                ('author', models.CharField(default='Не указан', max_length=100, verbose_name='Автор')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации курса')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('company', models.CharField(max_length=100, verbose_name='Название компании')),
                ('expirience', models.CharField(default='не указано', max_length=80, verbose_name='Срок курса')),
                ('salary', models.CharField(max_length=50, verbose_name='Стоимость курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('skills', models.CharField(max_length=255, verbose_name='Будущие навыки')),
                ('address', models.CharField(default='Алматы, Абая 52г', max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации курса')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.category', verbose_name='Выберите область')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
