# Generated by Django 5.1.3 on 2024-11-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.TextField(max_length=255, verbose_name='ответ'),
        ),
    ]
