# Generated by Django 5.1.3 on 2024-11-13 18:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0002_alter_test_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='ответ'),
        ),
    ]
